# Create repository /var/lib/zabbix on your Alpine Linux 
# Place  this file up to your repository 
# Change Database password 'StrongPass_123' to your own
# Run docker-compose up -d command and enjoy the magic of docker :)

version: "3.9"

networks:
  zabbix-network:
    ipam:
     driver: default
     config:
      - subnet: 172.22.1.0/24

services:

  postgres:
    image: postgres
    container_name: zabbix-pgsql
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: StrongPass_123
      POSTGRES_USER: zabbix
      PGDATA: data/postgres
    networks:
     zabbix-network:
       ipv4_address: 172.22.1.11
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: StrongPass_123
      ZBX_CACHESIZE: 1024M
      ZBX_STARTPINGERS: 10
      ZBX_STARTPOOLERS: 20
      ZBX_VALUECACHESIZE: 1024M
      ZBX_VMWARECACHESIZE: 256M
    networks:
     zabbix-network:
       ipv4_address: 172.22.1.12   
    restart: unless-stopped
    depends_on:
      - postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: StrongPass_123
      ZBX_SERVER_HOST: zabbix-server
    networks:
     zabbix-network:
       ipv4_address: 172.22.1.13
    ports:
      - 8080:8080
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: zabbix server
      ZBX_SERVER_HOST: zabbix-server
    networks:
     zabbix-network:
       ipv4_address: 172.22.1.14
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix-server
